var lookup_table = [
    {id:"larynx_tumor_type__patient",  english:"tumortype",  german:"Tumorentität"},
    {id:"larynx_tumor_type_clinical__patient",  english:"tumor type clinical",  german:"Klinische Tumorentität"},
    {id:"larynx_tumor_size__patient",  english:"tumorsize",  german:"Tumorgröße"},
    {id:"larynx_infiltration_extrinsic_muscle_tongue__patient",  english:"infiltration extrinsic tonguemuscle",  german:"Infiltration äuß. Zungenmuskeln"},
    {id:"larynx_infiltration_ACI_ACC__patient",  english:"infiltration ACI ACC",  german:"Infiltration ACI ACC"},
    {id:"larynx_infiltration_ACI_ACC_angiography__patient",  english:"ACI ACC angiography",  german:"Angiographie ACI ACC"},
    {id:"larynx_infiltration_pre_epiglottic_space__patient",  english:"pre epiglottic infiltration",  german:"Pre-epiglottische Infiltration"},
    {id:"larynx_infiltration_prevertebral_space__patient",  english:"prevertebral infiltration",  german:"Pre-vertebrale Infiltration"},
    {id:"larynx_infiltration_thyroid__patient",  english:"thyroid infiltration ",  german:"Schilddrüsen Infiltration"},
    {id:"larynx_infiltration_thyroid_PET_neck__patient",  english:"infiltration in PETscan",  german:"Infiltration im PET"},
    {id:"larynx_infiltration_trachea__patient",  english:"infiltration trachea",  german:"Infiltration Trachea"},
    {id:"larynx_infiltration_pyriform_sinus__patient",  english:"infiltration sinus pyriformis",  german:"Infiltration Rec. Piriformis"},
    {id:"larynx_infiltration_soft_tissue_neck__patient",  english:"infiltration soft tissue neck",  german:"Infiltration Halsweichteile"},
    {id:"larynx_infiltration_mediastinum__patient",  english:"infiltration mediastinum",  german:"Infiltration Mediastinum"},
    {id:"larynx_infiltration_tongue_base__patient",  english:"infiltration base of tonuge",  german:"Infiltration Zungengrund"},
    {id:"larynx_infiltration_esophagus__patient",  english:"infiltration esophagus",  german:"Infiltration Ösophagus"},
    {id:"other_location_M__patient",  english:"Metastases elsewhere",  german:"Weitere Metastasen"},
    {id:"larynx_infiltration_arytenoid_cartilage__patient",  english:"infiltration arytenoid cartilage",  german:"Infiltration Aryknorpel"},
    {id:"larynx_infiltration_strap_muscles__patient",  english:"infiltration strap muscles",  german:"Infiltration infrahyoidale Muskeln"},
    {id:"larynx_infiltration_postcricoid_area__patient",  english:"postcricoid infiltration ",  german:"postkrikoidale Infiltration"},
    {id:"larynx_infiltration_infrahyoid_epiglottis__patient",  english:"infiltration infrahyoid epiglottis",  german:"Infiltration infrahyoidaler Epiglottis"},
    {id:"larynx_tumor_localization__patient",  english:"tumorlocalization",  german:"Tumorlokalisation"},
    {id:"larynx_tumor_side__patient",  english:"side",  german:"Seite"},
    {id:"N_count__patient",  english:"Lymph node count",  german:"Zahl infiltrierter Lymphknoten"},
    {id:"larynx_infiltration_aryepiglottic_fold__patient",  english:"infiltration aryepiglottic fold",  german:"Infiltration Plica Aryepiglottica"},
    {id:"larynx_infiltration_esophagus_swallowing_Xray__patient",  english:"esophagus swallowing Xray",  german:"Ösophagusbreischluck"},
    {id:"larynx_infiltration_thyroid_cartilage__patient",  english:"infiltration thyroid cartilage",  german:"Infiltration Schildknorpel"},
    {id:"larynx_infiltration_commisures__patient",  english:"infiltration commisures",  german:"Infiltration Kommissuren"},
    {id:"larynx_infiltration_commisures_clinical_examination__patient",  english:"commisures clinical examination",  german:"Klinische Untersuchung Kommissuren"},
    {id:"larynx_infiltration_vallecula__patient",  english:"infiltration epiglottic vallecula",  german:"Infiltration Vallecula epiglottica"},
    {id:"larynx_infiltration_suprahyoid_epiglottis__patient",  english:"infiltration suprahyoid epiglottis",  german:"Infiltration suprahyoidale Epiglottis"},
    {id:"larynx_function_vocal_fold__patient",  english:"vocal fold function",  german:"Funktion Stimmlippe"},
    {id:"larynx_infiltration_vestibular_fold__patient",  english:"infiltration vestibular fold",  german:"Infiltration Taschenfalte"},
    {id:"larynx_infiltration_paraepiglottic_space__patient",  english:"paraepiglottic space infiltration",  german:"Paraepiglottische Infiltration"},
    {id:"larynx_infiltration_vocal_fold__patient",  english:"infiltration vocal fold",  german:"Infiltration Stimmlippe"},
    {id:"larynx_glottis_infiltration_subside__patient",  english:"glottis subside",  german:"Glottis Unterseite"},
    {id:"larynx_very_advanced_local_infiltration__patient",  english:"very advanced local infiltration",  german:"Lokal sehr fortgeschr. Infiltration"},
    {id:"larynx_supraglottis_infiltration_subsides__patient",  english:"supraglottis  subsides",  german:"Supraglottis Unterseiten"},
    {id:"larynx_advanced_local_infiltration__patient",  english:"advanced local infiltration",  german:"Lokal fortgeschrittene Infiltration"},
    {id:"larynx_infiltration_extrinsic_muscle_tongue_endoscopy__patient",  english:"endoscopy extrinsic tonguemuscle ",  german:"Endoskopie äuß. Zungenmuskeln"},
    {id:"larynx_infiltration_extrinsic_muscle_tongue_function__patient",  english:"extrinsic tonguemuscle function",  german:"Funktion äuß. Zungenmuskeln"},
    {id:"larynx_infiltration_extrinsic_muscle_tongue_intra_OP__patient",  english:"infiltration extrinsic tonguemuscle  intra OP",  german:"Intra OP äuß. Zungenmuskeln"},
    {id:"larynx_infiltration_extrinsic_muscle_tongue_CT_neck__patient",  english:"extrinsic tonguemuscle  CT neck",  german:"Äuß. Zungenmuskeln CT Hals"},
    {id:"larynx_infiltration_extrinsic_muscle_tongue_MRI_neck__patient",  english:"extrinsic tonguemuscle  MRI neck",  german:"Äuß. Zungenmuskeln MRT Hals"},
    {id:"larynx_infiltration_extrinsic_muscle_tongue_Sono_neck__patient",  english:"extrinsic tonguemuscle Sono neck",  german:"Äuß. Zungenmuskeln Sono Hals"},
    {id:"larynx_infiltration_extrinsic_muscle_tongue_PET_neck__patient",  english:"extrinsic tonguemuscle  PET neck",  german:"Äuß. Zungenmuskeln PET Hals"},
    {id:"larynx_infiltration_extrinsic_muscle_tongue_patho__patient",  english:"extrinsic tonguemuscle  patho",  german:"Äuß. Zungenmuskeln Patho"},
    {id:"larynx_infiltration_ACI_ACC_intra_OP__patient",  english:"ACI ACC intra OP",  german:"Intra OP ACI ACC"},
    {id:"larynx_infiltration_ACI_ACC_CT_neck__patient",  english:"ACI ACC CT neck",  german:"ACI ACC CT Hals"},
    {id:"larynx_infiltration_ACI_ACC_Sono_neck__patient",  english:"ACI ACC Sono neck",  german:"ACI ACC Sono Hals"},
    {id:"larynx_infiltration_ACI_ACC_MRI_neck__patient",  english:"ACI ACC MRI neck",  german:"ACI ACC MRI Hals"},
    {id:"larynx_infiltration_ACI_ACC_PET_neck__patient",  english:"ACI ACC PET neck",  german:" ACI ACC PET Hals"},
    {id:"larynx_infiltration_ACI_ACC_patho__patient",  english:"ACI ACC patho",  german:"ACI ACC Patho"},
    {id:"larynx_infiltration_pre_epiglottic_space_PET_neck__patient",  english:"pre epiglottic space PET neck",  german:"Präepiglottischer Raum PET Hals"},
    {id:"larynx_infiltration_pre_epiglottic_space_function__patient",  english:"pre epiglottic space function",  german:"Funktion Präepiglottischer Raum"},
    {id:"larynx_infiltration_pre_epiglottic_space_CT_neck__patient",  english:"pre epiglottic space CT neck",  german:"Präepiglottischer Raum CT Hals"},
    {id:"larynx_infiltration_pre_epiglottic_space_MRI_neck__patient",  english:"pre epiglottic space MRI neck",  german:"Präepiglottischer Raum MRT Hals"},
    {id:"larynx_infiltration_pre_epiglottic_space_patho__patient",  english:"pre epiglottic space patho",  german:"Präepiglottischer Raum Patho"},
    {id:"larynx_infiltration_pre_epiglottic_space_intra_OP__patient",  english:"pre epiglottic space infiltration intra OP",  german:"Intra OP Präepiglottischer Raum"},
    {id:"larynx_infiltration_pre_epiglottic_space_Sono_neck__patient",  english:"pre epiglottic space Sono neck",  german:"Präepiglottischer Raum Sono Hals"},
    {id:"larynx_infiltration_prevertebral_space_PET_neck__patient",  english:"prevertebral space PET neck",  german:"Prevertebraler Raum PET Hals"},
    {id:"larynx_infiltration_prevertebral_space_Sono_neck__patient",  english:"prevertebral space Sono neck",  german:"Prevertebraler Raum Sono Hals"},
    {id:"larynx_infiltration_prevertebral_space_patho__patient",  english:"prevertebral space patho",  german:"Prevertebraler Raum Patho"},
    {id:"larynx_infiltration_prevertebral_space_function__patient",  english:"prevertebral space function",  german:"Prevertebraler Raum Funktion"},
    {id:"larynx_infiltration_prevertebral_space_intra_OP__patient",  english:"prevertebral space intra OP",  german:"Intra OP Prevertebraler Raum "},
    {id:"larynx_infiltration_prevertebral_space_MRI_neck__patient",  english:"prevertebral space MRI neck",  german:"Prevertebraler Raum MRT Hals"},
    {id:"larynx_infiltration_prevertebral_space_endoscopy__patient",  english:"prevertebral space endoscopy",  german:"Prevertebraler Raum Endoskopie"},
    {id:"larynx_infiltration_prevertebral_space_CT_neck__patient",  english:"prevertebral space CT neck",  german:"Prevertebraler Raum CT Hals"},
    {id:"larynx_infiltration_thyroid_CT_neck__patient",  english:"thyroid CT neck",  german:"Schilddrüse CT Hals"},
    {id:"larynx_infiltration_thyroid_Sono_neck__patient",  english:"thyroid Sono neck",  german:"Schilddrüse Sono Hals"},
    {id:"larynx_infiltration_thyroid_intra_OP__patient",  english:"thyroid infiltration intra OP",  german:"Intra OP Schilddrüse"},
    {id:"larynx_infiltration_thyroid_function__patient",  english:"thyroid function",  german:"Funktion Schilddrüse"},
    {id:"larynx_infiltration_thyroid_MRI_neck__patient",  english:"thyroid MRI neck",  german:"Schilddrüse MRT Hals"},
    {id:"larynx_infiltration_thyroid_patho__patient",  english:"thyroid patho",  german:"Schilddrüse Patho"},
    {id:"larynx_infiltration_trachea_MRI_neck__patient",  english:"trachea MRI neck",  german:"Trachea MRT Hals"},
    {id:"larynx_infiltration_trachea_CT_neck__patient",  english:"trachea CT neck",  german:"Trachea CT Hals"},
    {id:"larynx_infiltration_trachea_function__patient",  english:"trachea function",  german:"Funktion Trachea"},
    {id:"larynx_infiltration_trachea_patho__patient",  english:"trachea patho",  german:"Trachea Patho"},
    {id:"larynx_infiltration_trachea_intra_OP__patient",  english:"trachea intra OP",  german:"Intra OP Trachea"},
    {id:"larynx_infiltration_trachea_endoscopy__patient",  english:"trachea endoscopy",  german:"Trachea Endoskopie"},
    {id:"larynx_infiltration_trachea_Sono_neck__patient",  english:"trachea Sono neck",  german:"Trachea Sono Hals"},
    {id:"larynx_infiltration_trachea_PET_neck__patient",  english:"trachea PET neck",  german:"Trachea PET Hals"},
    {id:"larynx_infiltration_pyriform_sinus_CT_neck__patient",  english:"pyriform sinus CT neck",  german:"Rec. Piriformis CT Hals"},
    {id:"larynx_infiltration_pyriform_sinus_intra_OP__patient",  english:"pyriform sinus intra OP",  german:"Intra OP Rec. Piriformis"},
    {id:"larynx_infiltration_pyriform_sinus_patho__patient",  english:"pyriform sinus patho",  german:"infiltration pyriform sinus patho"},
    {id:"larynx_infiltration_pyriform_sinus_endoscopy__patient",  english:"pyriform sinus endoscopy",  german:"Rec. Piriformis Endoskopie"},
    {id:"larynx_infiltration_pyriform_sinus_function__patient",  english:"pyriform sinus function",  german:"Funktion Rec. Piriformis "},
    {id:"larynx_infiltration_pyriform_sinus_PET_neck__patient",  english:"pyriform sinus PET neck",  german:"Rec. Piriformis PET Hals"},
    {id:"larynx_infiltration_pyriform_sinus_MRI_neck__patient",  english:"pyriform sinus MRI neck",  german:"Rec. Piriformis MRT Hals"},
    {id:"larynx_infiltration_soft_tissue_neck_CT_neck__patient",  english:"soft tissue neck CT neck",  german:"Halsweichteile CT Hals"},
    {id:"larynx_infiltration_soft_tissue_neck_Sono_neck__patient",  english:"soft tissue neck Sono neck",  german:"Halsweichteile Sono Hals"},
    {id:"larynx_infiltration_soft_tissue_neck_PET_neck__patient",  english:"soft tissue neck PET neck",  german:"Halsweichteile PET Hals"},
    {id:"larynx_infiltration_soft_tissue_neck_endoscopy__patient",  english:"soft tissue neck endoscopy",  german:"Halsweichteile Endoskopie"},
    {id:"larynx_infiltration_soft_tissue_neck_function__patient",  english:"soft tissue neck function",  german:"Funktion Halsweichteile "},
    {id:"larynx_infiltration_soft_tissue_neck_intra_OP__patient",  english:"soft tissue neck intra OP",  german:"Intra OP Halsweichteile "},
    {id:"larynx_infiltration_soft_tissue_neck_patho__patient",  english:"soft tissue neck patho",  german:"Halsweichteile Patho"},
    {id:"larynx_infiltration_soft_tissue_neck_MRI_neck__patient",  english:"soft tissue neck MRI neck",  german:"Halsweichteile MRT Hals"},
    {id:"larynx_infiltration_mediastinum_endosono__patient",  english:"mediastinum endosono",  german:"Mediastinum Endosono"},
    {id:"larynx_infiltration_mediastinum_patho__patient",  english:"mediastinum patho",  german:"Mediastinum Patho"},
    {id:"larynx_infiltration_mediastinum_CT_thorax__patient",  english:"mediastinum CT thorax",  german:"Mediastinum CT Thorax"},
    {id:"larynx_infiltration_mediastinum_MRI_thorax__patient",  english:"mediastinum MRI thorax",  german:"Mediastinum MRT Thorax"},
    {id:"larynx_infiltration_mediastinum_endoscopy__patient",  english:"mediastinum endoscopy",  german:"Mediastinum Endoskopie"},
    {id:"larynx_infiltration_mediastinum_PET_thorax__patient",  english:"mediastinum PET thorax",  german:"Mediastinum PET Thorax"},
    {id:"larynx_infiltration_mediastinum_intra_OP__patient",  english:"mediastinum intra OP",  german:"Intra OP Mediastinum"},
    {id:"larynx_infiltration_mediastinum_Sono_thorax__patient",  english:"mediastinum Sono thorax",  german:"Mediastinum Sono thorax"},
    {id:"larynx_infiltration_tongue_base_intra_OP__patient",  english:"base of tongue intra OP",  german:"Intra OP Zungengrund"},
    {id:"larynx_infiltration_tongue_base_PET_neck__patient",  english:"base of tongue PET neck",  german:"Zungengrund PET Hals"},
    {id:"larynx_infiltration_tongue_base_MRI_neck__patient",  english:"base of tongue MRI neck",  german:"Zungengrund MRT Hals"},
    {id:"larynx_infiltration_tongue_base_patho__patient",  english:"base of tongue patho",  german:"Zungengrund Patho"},
    {id:"larynx_infiltration_tongue_base_function__patient",  english:"base of tongue function",  german:"Funktion Zungengrund"},
    {id:"larynx_infiltration_tongue_base_CT_neck__patient",  english:"base of tongue CT neck",  german:"Zungengrund CT Hals"},
    {id:"larynx_infiltration_tongue_base_endoscopy__patient",  english:"base of tongue endoscopy",  german:"Zungengrund Endoskopie"},
    {id:"other_location_M_diagnostic__patient",  english:"other location M diagnostic",  german:"Weitere Metastasen Diagnostik"},
    {id:"larynx_infiltration_arytenoid_cartilage_endoscopy__patient",  english:"arytenoid cartilage endoscopy",  german:"Aryknorpel Endoskopie"},
    {id:"larynx_infiltration_arytenoid_cartilage_patho__patient",  english:"arytenoid cartilage patho",  german:"Aryknorpel Patho"},
    {id:"larynx_infiltration_arytenoid_cartilage_intra_OP__patient",  english:"arytenoid cartilage intra OP",  german:"Intra OP Aryknorpel"},
    {id:"larynx_infiltration_arytenoid_cartilage_MRI_neck__patient",  english:"arytenoid cartilage MRI neck",  german:"Aryknorpel MRT Hals"},
    {id:"larynx_infiltration_arytenoid_cartilage_PET_neck__patient",  english:"arytenoid cartilage PET neck",  german:"Aryknorpel PET Hals"},
    {id:"larynx_infiltration_arytenoid_cartilage_CT_neck__patient",  english:"arytenoid cartilage CT neck",  german:"Aryknorpel CT Hals"},
    {id:"larynx_infiltration_arytenoid_cartilage_function__patient",  english:"arytenoid cartilage function",  german:"Aryknorpel Funktion"},
    {id:"larynx_infiltration_strap_muscles_intra_OP__patient",  english:"strap muscles intra OP",  german:"Intra OP infrahyoidale Muskulatur"},
    {id:"larynx_infiltration_strap_muscles_patho__patient",  english:"strap muscles patho",  german:"Infrahyoidale Muskulatur patho"},
    {id:"larynx_infiltration_strap_muscles_function__patient",  english:"strap muscles function",  german:"Infrahyoidale Muskulatur Patho"},
    {id:"larynx_infiltration_strap_muscles_MRI_neck__patient",  english:"strap muscles MRI neck",  german:"Infrahyoidale Muskulatur MRT Hals"},
    {id:"larynx_infiltration_strap_muscles_CT_neck__patient",  english:"strap muscles CT neck",  german:"Infrahyoidale Muskulatur CT Hals"},
    {id:"larynx_infiltration_strap_muscles_endoscopy__patient",  english:"strap muscles endoscopy",  german:"Infrahyoidale Muskulatur Endoskopie"},
    {id:"larynx_infiltration_strap_muscles_PET_neck__patient",  english:"strap muscles PET neck",  german:"Infrahyoidale Muskulatur PET Hals"},
    {id:"larynx_infiltration_strap_muscles_Sono_neck__patient",  english:"strap muscles Sono neck",  german:"Infrahyoidale Muskulatur Sono Hals"},
    {id:"larynx_infiltration_postcricoid_area_PET_neck__patient",  english:"postcricoid area PET neck",  german:"Postkrikoidregion PET Hals"},
    {id:"larynx_infiltration_postcricoid_area_patho__patient",  english:"postcricoid area patho",  german:"Postkrikoidregion Patho"},
    {id:"larynx_infiltration_postcricoid_area_CT_neck__patient",  english:"postcricoid area CT neck",  german:"Postkrikoidregion CT Hals"},
    {id:"larynx_infiltration_postcricoid_area_intra_OP__patient",  english:"postcricoid area intra OP",  german:"Intra OP Postkrikoidregion"},
    {id:"larynx_infiltration_postcricoid_area_Sono_neck__patient",  english:"postcricoid area Sono neck",  german:"Postkrikoidregion Sono Hals"},
    {id:"larynx_infiltration_postcricoid_area_MRI_neck__patient",  english:"postcricoid area MRI neck",  german:"Postkrikoidregion MR Hals"},
    {id:"larynx_infiltration_postcricoid_area_function__patient",  english:"postcricoid area function",  german:"Postkrikoidregion Funktion"},
    {id:"larynx_infiltration_infrahyoid_epiglottis_MRI_neck__patient",  english:"infrahyoid epiglottis MRI neck",  german:"Infrahyoidale Epiglottis MRT Hals"},
    {id:"larynx_infiltration_infrahyoid_epiglottis_patho__patient",  english:"infrahyoid epiglottis patho",  german:"Infrahyoidale Epiglottis Patho"},
    {id:"larynx_infiltration_infrahyoid_epiglottis_endoscopy__patient",  english:"infrahyoid epiglottis endoscopy",  german:"Infrahyoidale Epiglottis Endoskopie"},
    {id:"larynx_infiltration_infrahyoid_epiglottis_CT_neck__patient",  english:"infrahyoid epiglottis CT neck",  german:"Infrahyoidale Epiglottis CT Hals"},
    {id:"larynx_infiltration_infrahyoid_epiglottis_function__patient",  english:"infrahyoid epiglottis function",  german:"Infrahyoidale Epiglottis Funktion"},
    {id:"larynx_infiltration_infrahyoid_epiglottis_PET_neck__patient",  english:"infrahyoid epiglottis PET neck",  german:"Infrahyoidale Epiglottis PET neck"},
    {id:"larynx_infiltration_infrahyoid_epiglottis_intra_OP__patient",  english:"infrahyoid epiglottis intra OP",  german:"Intra OP Infrahyoidale Epiglottis"},
    {id:"larynx_infiltration_aryepiglottic_fold_endoscopy__patient",  english:"aryepiglottic fold endoscopy",  german:"Plica aryepiglottica Endoskopie"},
    {id:"larynx_infiltration_aryepiglottic_fold_CT_neck__patient",  english:"aryepiglottic fold CT neck",  german:"Plica aryepiglottica CT Hals"},
    {id:"larynx_infiltration_aryepiglottic_fold_MRI_neck__patient",  english:"aryepiglottic fold MRI neck",  german:"Plica aryepiglottica MRT Hals"},
    {id:"larynx_infiltration_aryepiglottic_fold_function__patient",  english:"aryepiglottic fold function",  german:"Plica aryepiglottica Funktion"},
    {id:"larynx_infiltration_aryepiglottic_fold_patho__patient",  english:"aryepiglottic fold patho",  german:"Plica aryepiglottica Patho"},
    {id:"larynx_infiltration_aryepiglottic_fold_PET_neck__patient",  english:"aryepiglottic fold PET neck",  german:"Plica aryepiglottica PET Hals"},
    {id:"larynx_infiltration_aryepiglottic_fold_intra_OP__patient",  english:"aryepiglottic fold intra OP",  german:"Intra OP Plica aryepiglottica "},
    {id:"larynx_infiltration_esophagus_CT_neck__patient",  english:"esophagus CT neck",  german:"Ösophagus CT Hals"},
    {id:"larynx_infiltration_esophagus_Sono_neck__patient",  english:"esophagus Sono neck",  german:"Ösophagus Sono Hals"},
    {id:"larynx_infiltration_esophagus_Endosono_esophagus__patient",  english:"esophagus Endosono esophagus",  german:"Ösophagus Endosono"},
    {id:"larynx_infiltration_esophagus_function__patient",  english:"esophagus function",  german:"Ösophagus Funktion"},
    {id:"larynx_infiltration_esophagus_PET_neck__patient",  english:"esophagus PET neck",  german:"Ösophagus PET Hals"},
    {id:"larynx_infiltration_esophagus_patho__patient",  english:"esophagus patho",  german:"Ösophagus Patho"},
    {id:"larynx_infiltration_esophagus_intra_OP__patient",  english:"esophagus intra OP",  german:"Intra OP Ösophagus"},
    {id:"larynx_infiltration_esophagus_MRI_neck__patient",  english:"esophagus MRI neck",  german:"Ösophagus MRT Hals"},
    {id:"larynx_infiltration_esophagus_endoscopy__patient",  english:"esophagus endoscopy",  german:"Ösophagus Endoskopie"},
    {id:"larynx_infiltration_thyroid_cartilage_function__patient",  english:"thyroid cartilage function",  german:"Schildknorpel Funktion"},
    {id:"larynx_infiltration_thyroid_cartilage_CT_neck__patient",  english:"thyroid cartilage CT neck",  german:"Schildknorpel CT Hals"},
    {id:"larynx_infiltration_thyroid_cartilage_MRI_neck__patient",  english:"thyroid cartilage MRI neck",  german:"Schildknorpel MRT Hals"},
    {id:"larynx_infiltration_thyroid_cartilage_intra_OP__patient",  english:"thyroid cartilage intra OP",  german:"Schildknorpel intra OP"},
    {id:"larynx_infiltration_thyroid_cartilage_patho__patient",  english:"thyroid cartilage patho",  german:"Schildknorpel patho"},
    {id:"larynx_infiltration_thyroid_cartilage_Sono_neck__patient",  english:"thyroid cartilage Sono neck",  german:"Schildknorpel cartilage Sono neck"},
    {id:"larynx_infiltration_thyroid_cartilage_PET_neck__patient",  english:"thyroid cartilage PET neck",  german:"Schildknorpel PET Hals"},
    {id:"larynx_infiltration_commissures_MRI_neck__patient",  english:"commissures MRI neck",  german:"Kommissuren MRT Hals"},
    {id:"larynx_infiltration_commissures_intra_OP__patient",  english:"commissures intra OP",  german:"Intra OP Kommissuren"},
    {id:"larynx_infiltration_commissures_patho__patient",  english:"commissures patho",  german:"Kommissuren Patho"},
    {id:"larynx_infiltration_commissures_Sono_neck__patient",  english:"commisures Sono neck",  german:"Kommissuren Sono Hals"},
    {id:"larynx_infiltration_commissures_CT_neck__patient",  english:"commissures CT neck",  german:"Kommissuren CT Hals"},
    {id:"larynx_infiltration_commissures_endoscopy__patient",  english:"commissures endoscopy",  german:"Kommissuren Endoskopie"},
    {id:"larynx_infiltration_vallecula_MRI_neck__patient",  english:"vallecula MRI neck",  german:"Vallecula MRI Hals"},
    {id:"larynx_infiltration_vallecula_CT_neck__patient",  english:"vallecula CT neck",  german:"Vallecula CT Hals"},
    {id:"larynx_infiltration_vallecula_endoscopy__patient",  english:"vallecula endoscopy",  german:"Vallecula Endoskopie"},
    {id:"larynx_infiltration_vallecula_intra_OP__patient",  english:"vallecula intra OP",  german:"Intra OP Vallecula"},
    {id:"larynx_infiltration_vallecula_patho__patient",  english:"vallecula patho",  german:"Vallecula Patho"},
    {id:"larynx_infiltration_vallecula_function__patient",  english:"vallecula function",  german:"Vallecula Funktion"},
    {id:"larynx_infiltration_vallecula_PET_neck__patient",  english:"vallecula PET neck",  german:"Vallecula PET Hals"},
    {id:"larynx_tumor_localization_patho__patient",  english:"tumor localization patho",  german:"Tumor Lokalisation Patho"},
    {id:"larynx_tumor_localization_CT_neck__patient",  english:"tumor localization CT neck",  german:"Tumor Lokalisation CT Hals"},
    {id:"larynx_tumor_localization_clinical_exam__patient",  english:"tumor localization clinical exam",  german:"Tumor Lokalisation klinische Untersuchung"},
    {id:"larynx_tumor_localization_Sono_neck__patient",  english:"tumor localization Sono neck",  german:"Tumor Lokalisation Sono Hals"},
    {id:"larynx_tumor_localization_endoscopy__patient",  english:"tumor localization endoscopy",  german:"Tumor Lokalisation Endoskopie"},
    {id:"larynx_tumor_localization_PET_neck__patient",  english:"tumor localization PET neck",  german:"Tumor Lokalisation PET Hals"},
    {id:"larynx_tumor_localization_MRT_neck__patient",  english:"tumor localization MRT neck",  german:"Tumor Lokalisation MRT Hals"},
    {id:"N_count_palpation__patient",  english:"Lymph node count palpation",  german:"Lymphknoten Anzahl Palpation"},
    {id:"N_count_patho__patient",  english:"Lymph node count patho",  german:"Lymphknoten Anzahl Patho"},
    {id:"N_count_Sono__patient",  english:"Lymph node count Sono",  german:"Lymphknoten Anzahl Sono"},
    {id:"larynx_infiltration_suprahyoid_epiglottis_intra_OP__patient",  english:"suprahyoid epiglottis intra OP",  german:"Intra OP Suprahyoidale Epiglottis"},
    {id:"larynx_infiltration_suprahyoid_epiglottis_PET_neck__patient",  english:"suprahyoid epiglottis PET neck",  german:"Suprahyoidale Epiglottis PET Hals"},
    {id:"larynx_infiltration_suprahyoid_epiglottis_CT_neck__patient",  english:"suprahyoid epiglottis CT neck",  german:"Suprahyoidale Epiglottis CT Hals"},
    {id:"larynx_infiltration_suprahyoid_epiglottis_patho__patient",  english:"suprahyoid epiglottis patho",  german:"Suprahyoidale Epiglottis Patho"},
    {id:"larynx_infiltration_suprahyoid_epiglottis_function__patient",  english:"suprahyoid epiglottis function",  german:"Suprahyoidale Epiglottis Funktion"},
    {id:"larynx_infiltration_suprahyoid_epiglottis_MRI_neck__patient",  english:"suprahyoid epiglottis MRI neck",  german:"Suprahyoidale Epiglottis MRT Hals"},
    {id:"larynx_infiltration_suprahyoid_epiglottis_endoscopy__patient",  english:"suprahyoid epiglottis endoscopy",  german:"Suprahyoidale Epiglottis Endoskopie"},
    {id:"larynx_function_vocal_fold_dyspnea__patient",  english:"function vocal fold dyspnea",  german:"Funktion Stimmlippe Dyspnoe"},
    {id:"larynx_function_vocal_fold_stroboscopy__patient",  english:"function vocal fold stroboscopy",  german:"Funktion Stimmlippe Stroboskopie"},
    {id:"larynx_function_vocal_fold_clinical_examination__patient",  english:"function vocal fold clinical examination",  german:"Funktion Stimmlippe Klinische Untersuchung"},
    {id:"larynx_infiltration_vestibular_fold_CT_neck__patient",  english:"vestibular fold CT neck",  german:"Taschenfalte CT Hals"},
    {id:"larynx_infiltration_vestibular_fold_endoscopy__patient",  english:"vestibular fold endoscopy",  german:"Taschenfalte Endoskopie"},
    {id:"larynx_infiltration_vestibular_fold_PET_neck__patient",  english:"vestibular fold PET neck",  german:"Taschenfalte PET Hals"},
    {id:"larynx_infiltration_vestibular_fold_function__patient",  english:"vestibular fold function",  german:"Taschenfalte Funktion"},
    {id:"larynx_infiltration_vestibular_fold_MRI_neck__patient",  english:"vestibular fold MRI neck",  german:"Taschenfalte MRT Hals"},
    {id:"larynx_infiltration_vestibular_fold_patho__patient",  english:"vestibular fold patho",  german:"Taschenfalte Patho"},
    {id:"larynx_infiltration_vestibular_fold_intra_OP__patient",  english:"vestibular fold intra OP",  german:"Intra OP Taschenfalte"},
    {id:"larynx_infiltration_paraepiglottic_space_intra_OP__patient",  english:"paraepiglottic space intra OP",  german:"Intra OP paraglottischer Raum"},
    {id:"larynx_infiltration_paraepiglottic_space_function__patient",  english:"paraepiglottic space function",  german:"Funktion paraglottischer Raum"},
    {id:"larynx_infiltration_paraepiglottic_space_MRI_neck__patient",  english:"paraepiglottic space MRI neck",  german:"Paraglottischer Raum MRT Hals"},
    {id:"larynx_infiltration_paraepiglottic_space_Sono_neck__patient",  english:"paraepiglottic space Sono neck",  german:"Paraglottischer Raum Sono Hals"},
    {id:"larynx_infiltration_paraepiglottic_space_patho__patient",  english:"paraepiglottic space patho",  german:"Paraglottischer Raum Patho"},
    {id:"larynx_infiltration_paraepiglottic_space_PET_neck__patient",  english:"paraepiglottic space PET neck",  german:"Paraglottischer Raum PET Hals"},
    {id:"larynx_infiltration_paraepiglottic_space_CT_neck__patient",  english:"paraepiglottic space CT neck",  german:"Paraglottischer Raum CT Hals"},
    {id:"larynx_infiltration_vocal_fold_endoscopy__patient",  english:"vocal fold endoscopy",  german:"Stimmlippe Endoskopie"},
    {id:"larynx_infiltration_vocal_fold_clinical_examination__patient",  english:"vocal fold clinical examination",  german:"Stimmlippe klinische Untersuchung"},
    {id:"larynx_infiltration_vocal_fold_patho__patient",  english:"vocal fold patho",  german:"Stimmlippe Patho"},
    {id:"larynx_infiltration_vocal_fold_CT_neck__patient",  english:"vocal fold CT neck",  german:"Stimmlippe CT Hals"},
    {id:"larynx_infiltration_vocal_fold_MRI_neck__patient",  english:"vocal fold MRI neck",  german:"Stimmlippe MRT Hals"},
    {id:"larynx_infiltration_vocal_fold_intra_OP__patient",  english:"vocal fold intra OP",  german:"Intra OP Stimmlippe"},
    {id:"larynx_infiltration_vocal_fold_Sono_neck__patient",  english:"vocal fold Sono neck",  german:"Stimmlippe Sono Hals"},
    {id:"T3_criteria__patient",  english:"T3 criteria",  german:"T3 Kriterien"},
    {id:"larynx_T_state__patient",  english:"T state",  german:"T-Status"},
    {id:"larynx_tumor_side_endoscopy__patient",  english:"tumor side endoscopy",  german:"Tumorseite Endoskopie"},
    {id:"larynx_tumor_side_clinical_exam_neck__patient",  english:"tumor side clinical exam neck",  german:"Tumorseite klinische Untersuchung Hals"},
    {id:"larynx_tumor_side_CT_neck__patient",  english:"tumor side CT neck",  german:"Tumorseite CT Hals"},
    {id:"larynx_tumor_side_Sono_neck__patient",  english:"tumor side Sono neck",  german:"Tumorseite Sono Hals"},
    {id:"larynx_tumor_side_patho__patient",  english:"tumor side patho",  german:"Tumorseite Patho"},
    {id:"larynx_tumor_side_MRT_neck__patient",  english:"tumor side MRT neck",  german:"Tumorseite MRT Hals"},
    {id:"larynx_tumor_side_PET_neck__patient",  english:"tumor side PET neck",  german:"tumor side PET neck"},
    {id:"N_size__patient",  english:"Lymph node size",  german:"Lymphknoten Größe"},
    {id:"N_position__patient",  english:"Lymph node position",  german:"Lymphknoten Position"},
    {id:"bone_M__patient",  english:"bone metastases",  german:"Knochenmetastasen"},
    {id:"peritoneum_M__patient",  english:"peritoneum mestastases",  german:"Peritoneale Metastasen"},
    {id:"skin_M__patient",  english:"skin mestastases",  german:"Hautmetastasen"},
    {id:"hepar_M__patient",  english:"liver metastases ",  german:"Lebermetastasen"},
    {id:"distant_lymphnode_M__patient",  english:"distant lymph node metastases",  german:"Fernmetastasierung Lymphkn."},
    {id:"N_positive_size_palpation__patient",  english:"Lymph node size pos palpation",  german:"Lymphknoten Größe pos Palpation"},
    {id:"N_positive_size_MRI_neck__patient",  english:"Lymph node size pos MRI neck",  german:"Lymphknoten Größe pos MRT Hals"},
    {id:"N_positive_size_PET_neck__patient",  english:"Lymph node size pos PET neck",  german:"Lymphknoten Größe pos PET Hals"},
    {id:"N_positive_size_patho__patient",  english:"Lymph node size pos patho",  german:"Lymphknoten Größe pos Patho"},
    {id:"N_positive_size_CT_neck__patient",  english:"Lymph node size pos CT neck",  german:"Lymphknoten Größe pos CT Hals"},
    {id:"N_positive_size_sono__patient",  english:"Lymph node size pos sono",  german:"Lymphknoten Größe pos Sono"},
    {id:"N_positive_side_palpation__patient",  english:"Lymph node side pos palpation",  german:"Lymphknoten Seite pos Palpation"},
    {id:"N_positive_side_PET_neck__patient",  english:"Lymph node side pos PET neck",  german:"Lymphknoten Seite pos PET Hals"},
    {id:"N_positive_side_CT_neck__patient",  english:"Lymph node side pos CT neck",  german:"Lymphknoten Seite pos CT Hals"},
    {id:"N_positive_side_MRI_neck__patient",  english:"Lymph node side pos MRI neck",  german:"Lymphknoten Seite pos MRT Hals"},
    {id:"N_positive_side_sono__patient",  english:"Lymph node side pos sono",  german:"Lymphknoten Seite pos Sono"},
    {id:"N_positive_side_patho__patient",  english:"Lymph node side pos patho",  german:"Lymphknoten Seite pos Patho"},
    {id:"bone_M_PET_body__patient",  english:"bone metastases PET body",  german:"Knochenmetastasen PET"},
    {id:"bone_M_Scinti__patient",  english:"bone metastases Scinti",  german:"Knochenmetastasen Scinti"},
    {id:"bone_M_CT_body__patient",  english:"bone metastases CT body",  german:"Knochenmetastasen CT "},
    {id:"bone_M_fracture__patient",  english:"bone metastases fracture",  german:"Knochenmetastasen Fraktur"},
    {id:"perit_M_CT_abdomen__patient",  english:"peritoneal metastases CT abdomen",  german:"Peritoneale M CT Abdomen"},
    {id:"perit_M_Sono_abdomen__patient",  english:"peritoneal metastases Sono abdomen",  german:"Peritoneale M Sono Abdomen"},
    {id:"others_M_Sono_abdomen__patient",  english:"others metastases Sono abdomen",  german:"weitere M Sono Abdomen"},
    {id:"others_M_CT_abdomen__patient",  english:"others M CT abdomen",  german:"weitere M CT Abdomen"},
    {id:"hep_M_CT_abdomen__patient",  english:"liver metastases CT abdomen",  german:"Leber-M CT Abdomen"},
    {id:"hep_M_Sono_abdomen__patient",  english:"liver metastases Sono abdomen",  german:"Leber-M Sono Abdomen"},
    {id:"hep_M_CT_GuidedPunction__patient",  english:"liver metastases CT GuidedPunction",  german:"Leber-M CT-gestütze Punktion"},
    {id:"hep_M_Sono_GuidedPunction__patient",  english:"liver metastases Sono GuidedPunction",  german:"Leber-M Sono-gestütze Punktion"},
    {id:"distant_lymphnode_PET_thorax__patient",  english:"distant lymphnode PET thorax",  german:"Ferne Lymphknoten PET Thorax"},
    {id:"distant_lymphnode_CR_thorax__patient",  english:"distant lymphnode CR thorax",  german:"Ferne Lymphknoten CR Thorax"},
    {id:"distant_lymphnode_endosono__patient",  english:"distant lymphnode endosono",  german:"Ferne Lymphknoten Endosono"},
    {id:"distant_lymphnode_CT_thorax__patient",  english:"distant lymphnode CT thorax",  german:"Ferne Lymphknoten CT Thorax"},
    {id:"N_state__patient",  english:"N state",  german:"N Status"},
    {id:"pulmonary_M__patient",  english:"pulmonary metastases",  german:"Lungenmetastasen"},
    {id:"pleura_M__patient",  english:"pleural metastases",  german:"Pleurametastasen"},
    {id:"brain_M__patient",  english:"brain metastases",  german:"Hirnmetastasen"},
    {id:"bonemarrow_M__patient",  english:"bonemarrow metastases",  german:"Knochenmarkmetastasen"},
    {id:"pul_M_CR_thorax__patient",  english:"pulmonary metastases CR thorax",  german:"Lungenmetastasen CR Thorax"},
    {id:"pul_M_CT_thorax__patient",  english:"pulmonary metastases CT thorax",  german:"Lungenmetastasen CT Thorax"},
    {id:"pul_M_PET_thorax__patient",  english:"pulmonary metastases PET thorax",  german:"Lungenmetastasen PET Thorax"},
    {id:"pul_M_bronchoscopy__patient",  english:"pulmonary metastases bronchoscopy",  german:"Lungenmetastasen Bronchoskopie"},
    {id:"pulmonary_M_CT_GuidedPunction__patient",  english:"pulmonary metastases  CT guided punction",  german:"Lungenmetastasen CT-gestützte Punktion"},
    {id:"pulmonary_M_bronchoscopy_GuidedPunction__patient",  english:"pulmonary metastases bronchoscopy guided punction",  german:"Lungenmetastasen Bronchoskopie-gestützte Punktion"},
    {id:"pleu_M_CR_thorax__patient",  english:"pleural metastases CR thorax",  german:"Pleurametastasen CR Thorax"},
    {id:"pleu_M_PET_thorax__patient",  english:"pleural metastases PET thorax",  german:"Pleurametastasen PET Thorax"},
    {id:"pleu_M_CT_thorax__patient",  english:"pleural metastases CT thorax",  german:"Pleurametastasen CT Thorax"},
    {id:"brain_M_cMRT__patient",  english:"brain metastases cMRT",  german:"Hirnmetastasen cMRT"},
    {id:"brain_M_cCT__patient",  english:"brain metastases cCT",  german:"Hirnmetastasen cCT"},
    {id:"brain_M_PET__patient",  english:"brain metastases PET",  german:"Hirnmetastasen PET"},
    {id:"bm_M_PET_body__patient",  english:"bonemarrow metastases PET body",  german:"Knochenmarkmetastasen PET body"},
    {id:"bm_M_CR_body__patient",  english:"bonemarrow metastases CR body",  german:"Knochenmarkmetastasen CR body"},
    {id:"bm_M_Scinti__patient",  english:"bonemarrow metastases Scinti",  german:"Knochenmarkmetastasen Scinti"},
    {id:"bm_M_CT_body__patient",  english:"bonemarrow metastases CT body",  german:"Knochenmarkmetastasen CT body"},
    {id:"M_state__patient",  english:"M state",  german:"M Status"},
    {id:"UICC_stage__patient",  english:"UICC stage",  german:"UICC Stadien"},
    {id:"N_count_CT_neck__patient",  english:"Lymph node count CT neck",  german:"Lymphknoten Zahl CT Hals"},
    {id:"N_count_MRI_neck__patient",  english:"Lymph node count MRI neck",  german:"Lymphknoten Zahl MRT Hals"},
    {id:"N_count_PET_neck__patient",  english:"Lymph node count PET neck",  german:"Lymphknoten Zahl PET Hals"},
    {id:"pleu_M_guidedPunction__patient",  english:"pleural metastases guided punction",  german:"Pleurametastasen geführte Punktion"},
    {id:"larynx_infiltration_postcricoid_area_endoscopy__patient",  english:"postcricoid area endoscopy",  german:"Postkrikoidaler Raum Endoskopie"},
    {id:"larynx_infiltration_pre_epiglottic_space_endoscopy__patient",  english:"pre epiglottic space endoscopy",  german:"Präepiglottischer Raum Endoskopie"},
    {id:"larynx_infiltration_paraepiglottic_space_endoscopy__patient",  english:" paraepiglottic space endoscopy",  german:"Paraepiglottischer Raum Endoskopie"},
    {id:"larynx_infiltration_thyroid_cartilage_endoscopy__patient",  english:"thyroid cartilage endoscopy",  german:"Schildknorpel Endoskopie"},
    {id:"larynx_tumor_type_pathohisto__patient",  english:"tumor type pathohisto",  german:"Tumorentität Histopatho"},
    {id:"larynx_tumor_size_MRT_neck__patient",  english:"tumor size MRT neck",  german:"Tumorgröße MRT Hals"},
    {id:"larynx_tumor_size_Sono_neck__patient",  english:"tumor size Sono neck",  german:"Tumorgröße Sono Hals"},
    {id:"larynx_tumor_size_CT_neck__patient",  english:"tumor size CT neck",  german:"Tumorgröße CT Hals"},
    {id:"larynx_tumor_size_endoscopy__patient",  english:"tumor size endoscopy",  german:"Tumorgröße Endoskopie"},
    {id:"larynx_tumor_size_PET_neck__patient",  english:"tumor size PET neck",  german:"Tumorgröße PET Hals"},
    {id:"larynx_tumor_size_clinical_examination__patient",  english:"tumor size clinical examination",  german:"Tumorgröße klinische Untersuchung"},
    {id:"larynx_tumor_size_patho__patient",  english:"tumor size patho",  german:"Tumorgröße Patho"}
];

function lookup_table_get_name_by_id(id) {
    var result = lookup_table.filter(function (obj) {
        return obj.id === id;
    });

    if (result.length === 0) {
        return id;
    } else {
        if (default_language === language_english) {
            return result[0].english;
        } else if (default_language === language_german) {
            return result[0].german;
        }
    }
}

function lookup_table_get_id_by_name(name) {
    var result = lookup_table.filter(function (obj) {
        return obj.english === name || obj.german === name;
    });

    if (result.length === 0) {
        return name;
    } else {
        return result[0].id;
    }
}