
function return_by_stage_html_code() {
    return "<h1>Treating Laryngeal and Hypopharyngeal Cancers by Stage</h1><p>Most of the time, the treatment of <a href=\"https://www.cancer.org/cancer/laryngeal-and-hypopharyngeal-cancer/about/what-is-laryngealand-hypopharyngeal.html\">laryngeal or hypopharyngeal cancer</a> is based on its <a href=\"https://www.cancer.org/cancer/laryngeal-and-hypopharyngeal-cancer/detection-diagnosis-staging/staging.html\">stage</a> – how far it has spread. But other factors, such as your overall health and your personal preferences, may also affect treatment options. Talk to your doctor if you have any <a href=\"https://www.cancer.org/cancer/laryngeal-and-hypopharyngeal-cancer/detection-diagnosis-staging/talking-with-doctor.html\">questions</a> about the treatment plan he or she recommends. Make sure you understand the <a href=\"https://www.cancer.org/treatment/understanding-your-diagnosis/after-diagnosis/making-treatment-decisions.html\">goal of treatment</a>. Ask how treatment will change how you look, talk, breathe, and eat.</p> \n" +
        "  <h2>Laryngeal cancers</h2> \n" +
        "  <h3>Stage 0</h3> \n" +
        "  <p>These cancers are almost always glottic (vocal cord) cancers that are found early because of voice changes. They are nearly always curable with either <a href=\"https://www.cancer.org/cancer/laryngeal-and-hypopharyngeal-cancer/treating/surgery.html\">endoscopic surgery</a> or <a href=\"https://www.cancer.org/cancer/laryngeal-and-hypopharyngeal-cancer/treating/radiation.html\">radiation therapy</a>. The patient is then watched closely to see if the cancer returns. If the cancer does comes back, radiation can be used.</p> \n" +
        "  <p>Almost all people at this stage can be cured without major surgery. But it's important for them to know that if they smoke, continuing to do so makes treatment less likely to work and increases the risk that another tumor will develop.</p> \n" +
        "  <h3>Stage I and II laryngeal cancers</h3> \n" +
        "  <p>Most people with stage I and II laryngeal cancers can be treated successfully without totally removing their larynx.</p> \n" +
        "  <p>Either <a href=\"https://www.cancer.org/cancer/laryngeal-and-hypopharyngeal-cancer/treating/radiation.html\">radiation</a> alone (without surgery) or <a href=\"https://www.cancer.org/cancer/laryngeal-and-hypopharyngeal-cancer/treating/surgery.html\">partial laryngectomy</a> can be used in most people. Many doctors use radiation therapy for smaller cancers. Voice results tend to be better with radiation therapy than with partial laryngectomy, and there tend to be fewer problems with radiation treatment. </p> \n" +
        "  <p>The treatment for glottic (vocal cord) cancers and supraglottic cancers (those starting above the vocal cords) is slightly different. Some early glottic cancers may be treated by removing the vocal cord with cancer (<a href=\"https://www.cancer.org/cancer/laryngeal-and-hypopharyngeal-cancer/treating/surgery.html\">cordectomy</a>), or even by <a href=\"https://www.cancer.org/cancer/laryngeal-and-hypopharyngeal-cancer/treating/surgery.html\">laser surgery</a>. <a href=\"https://www.cancer.org/cancer/laryngeal-and-hypopharyngeal-cancer/treating/radiation.html\">Radiation</a> or <a href=\"https://www.cancer.org/cancer/laryngeal-and-hypopharyngeal-cancer/treating/surgery.html\">surgery</a> is usually enough to treat most glottic cancers unless there are signs that the treatment might not have cured the cancer (such as finding cancer cells at the edge of the removed tumor). If you need more treatment after surgery, your options might include radiation therapy, <a href=\"https://www.cancer.org/cancer/laryngeal-and-hypopharyngeal-cancer/treating/chemotherapy.html\">chemoradiation</a>, or surgery to remove more of the larynx.</p> \n" +
        "  <p>Supraglottic cancers are more likely to spread to the neck <a href=\"https://www.cancer.org/cancer/cancer-basics/lymph-nodes-and-cancer.html\">lymph nodes</a>. If so, the nodes are treated too. If you're having surgery for your tumor (supraglottic laryngectomy), then the surgeon may remove lymph nodes from your neck (called a lymph node dissection). If your treatment is radiation therapy alone, you will also get radiation to the lymph nodes in the neck. If, after surgery, the cancer is found to have features that make it more likely to come back, more treatment such as radiation therapy, chemoradiation, or more extensive surgery may be needed.</p> \n" +
        "  <h3>Stage III and IV laryngeal cancers</h3> \n" +
        "  <p>Stage III and IV laryngeal cancers are often treated with some combination of <a href=\"https://www.cancer.org/cancer/laryngeal-and-hypopharyngeal-cancer/treating/surgery.html\">surgery</a>, <a href=\"https://www.cancer.org/cancer/laryngeal-and-hypopharyngeal-cancer/treating/radiation.html\">radiation</a>, and/or <a href=\"https://www.cancer.org/cancer/laryngeal-and-hypopharyngeal-cancer/treating/chemotherapy.html\">chemotherapy</a>.</p> \n" +
        "  <p>The main options for initial treatment are surgery or chemotherapy with radiation. Radiation therapy alone (or with the <a href=\"https://www.cancer.org/cancer/laryngeal-and-hypopharyngeal-cancer/treating/targeted-therapy.html\">targeted drug cetuximab</a>) may be an option for people who cannot tolerate more intensive treatments.</p> \n" +
        "  <p>Surgery for these tumors is almost always complete removal of the larynx (total laryngectomy), but a small number of these cancers might be treated by partial laryngectomy.</p> \n" +
        "  <p>At this stage, these cancers have a higher risk of spreading to nearby <a href=\"https://www.cancer.org/cancer/cancer-basics/lymph-nodes-and-cancer.html\">lymph nodes</a> in the neck, so these lymph nodes are often removed along with the tumor if surgery is being done. Radiation therapy, often given with chemo, may be needed after surgery, especially if the cancer has spread to the lymph nodes or has other features that make it more likely to come back.</p> \n" +
        "  <p>Instead of using surgery as the first step, many doctors now prefer to start treatment with chemoradiation (radiation and chemotherapy given together). If any cancer remains after treatment, surgery can then be done to try to remove it. This treatment can be difficult, but it works as well as total laryngectomy and gives a chance to save the larynx. If the framework of the larynx (such as the thyroid cartilage) has been destroyed by the cancer, the larynx may never work normally again, no matter what treatment is chosen. In these cases, the best treatment  may be surgery to remove the larynx and nearby tissues with cancer (such as the thyroid gland).</p> \n" +
        "  <p>Another option may be to start with just chemotherapy, which is called <em>induction chemotherapy</em>. If the tumor shrinks, radiation therapy or chemoradiation is then given. If the tumor doesn’t shrink, surgery is usually the next treatment. </p> \n" +
        "  <p>Cancers that are too big or have spread too far to be completely removed by surgery are often treated with radiation, usually combined with chemotherapy or  cetuximab. Sometimes, if the tumor shrinks enough, surgery of lymph nodes in the neck may be an option. But for many advanced cancers, the goal of treatment is often to stop or slow the growth of the cancer for as long as possible and to help relieve any symptoms it may be causing.</p> \n" +
        "  <p>Most experts agree that treatment in a <a href=\"https://www.cancer.org/treatment/treatments-and-side-effects/clinical-trials.html\">clinical trial</a> should be considered for advanced stage laryngeal cancers. \n" +
        "    This way patients can get the best treatment available now and may also get the treatments that are thought to be even better.</p> \n" +
        "  <h2>Hypopharyngeal cancers</h2> \n" +
        "  <p>These cancers are often harder to treat than laryngeal cancers. Because they don't cause symptoms when they're small, most are already at an advanced <a href=\"https://www.cancer.org/cancer/laryngeal-and-hypopharyngeal-cancer/detection-diagnosis-staging/hypopharyngeal-staging.html\">stage</a> when they're diagnosed. Tumors in this area also tend to spread to the <a href=\"https://www.cancer.org/cancer/cancer-basics/lymph-nodes-and-cancer.html\">lymph nodes</a>, even when there's no obvious mass in the neck. Because of this, treatment of the lymph nodes in the neck is often recommended.</p> \n" +
        "  <h3>Stage I hypopharyngeal cancers</h3> \n" +
        "  <p>The main options for initial treatment of these cancers are <a href=\"https://www.cancer.org/cancer/laryngeal-and-hypopharyngeal-cancer.html\">surgery</a> with or without <a href=\"https://www.cancer.org/cancer/laryngeal-and-hypopharyngeal-cancer/treating/radiation.html\">radiation</a> to the lymph nodes.</p> \n" +
        "  <p>Surgery includes removing all or part of the pharynx (throat) as well as lymph nodes on both sides of the neck (lymph node dissection). The larynx (voice box) often needs to be removed as well. People who have a high chance of the cancer returning (based on what's found during surgery) may then be treated with radiation or <a href=\"https://www.cancer.org/cancer/laryngeal-and-hypopharyngeal-cancer/treating/chemotherapy.html\">chemotherapy</a> combined with radiation (chemoradiation).</p> \n" +
        "  <p>Some patients with small tumors may get radiation as their main treatment. The cancer is assessed again after the treatment is complete and if there's any cancer left, surgery is done.</p> \n" +
        "  <h3>Stages II, III, and IV hypopharyngeal cancers</h3> \n" +
        "  <p>There are 3 main options to treat these cancers.</p> \n" +
        "  <p>The first is <a href=\"https://www.cancer.org/cancer/laryngeal-and-hypopharyngeal-cancer/treating/surgery.html\">surgery</a> to remove the pharynx, larynx, and <a href=\"https://www.cancer.org/cancer/cancer-basics/lymph-nodes-and-cancer.html\">lymph nodes</a> in the neck. This is usually followed by <a href=\"https://www.cancer.org/cancer/laryngeal-and-hypopharyngeal-cancer/treating/radiation.html\">radiation</a> alone or radiation with <a href=\"https://www.cancer.org/cancer/laryngeal-and-hypopharyngeal-cancer/treating/chemotherapy.html\">chemo</a>, especially if there's a high chance that the cancer will come back based on what is found during surgery.</p> \n" +
        "  <p>Another option is to be treated first with radiation or both radiation and chemo (<a href=\"https://www.cancer.org/cancer/laryngeal-and-hypopharyngeal-cancer/treating/radiation.html\">chemoradiation</a>). If any cancer remains after treatment, surgery can then be done to try to remove it.</p> \n" +
        "  <p>The third option is to get chemotherapy as the first treatment, called <em>induction chemotherapy</em>. This is usually followed by radiation therapy or chemoradiation, depending on how much the tumor shrinks. If the tumor does not shrink, surgery might be done. If the lymph nodes in the neck are still enlarged after treatment, surgery can be done to remove them (lymph node dissection).</p> \n" +
        "  <p>Cancers that are too big or have spread too far to be completely removed by surgery are often treated with radiation, usually combined with chemo or <a href=\"https://www.cancer.org/cancer/laryngeal-and-hypopharyngeal-cancer/treating/targeted-therapy.html\">cetuximab</a>. Sometimes, if the tumor shrinks enough, surgery of lymph nodes in the neck may be an option. But for many advanced cancers, the goal of treatment is often to stop or slow the growth of the cancer for as long as possible and to help relieve any symptoms it may be causing.</p> \n" +
        "  <p>Most experts agree that treatment in a <a href=\"https://www.cancer.org/treatment/treatments-and-side-effects/clinical-trials.html\">clinical trial</a> should be considered for advanced stage hypopharygeal cancers. This way patients can get the best treatment available now and may also get the treatments that are thought to be even better.</p> " +

        "<p>\n Source: <a href=\"https://www.cancer.org/cancer/acs-medical-content-and-news-staff.html\">The American Cancer Society medical and editorial content team.</a> November 27, 2017 </p>";

        // "   <h2>Written by</h2> \n" +
        // " <div class='logo-info rich-content'><p><a href='https://www.cancer.org/cancer/acs-medical-content-and-news-staff.html'>The American Cancer Society medical and editorial content team<br /> \n" +
        // "</a>Our team is made up of doctors and master's-prepared nurses with deep knowledge of cancer care as well as journalists, editors, and translators with extensive experience in medical writing.</p> \n" +
        // "</div> \n" +
        // "</div>";
}