
function return_surgery_html_code() {
    return "<h1>Surgery for Laryngeal and Hypopharyngeal Cancers</h1>" +
        "<p>Surgery is commonly used to treat <a href=\"https://www.cancer.orghttps://www.cancer.org/cancer/laryngeal-and-hypopharyngeal-cancer/about/what-is-laryngealand-hypopharyngeal.html\">laryngeal and hypopharyngeal cancers</a>. Depending on the type, <a href=\"https://www.cancer.orghttps://www.cancer.org/cancer/laryngeal-and-hypopharyngeal-cancer/detection-diagnosis-staging/staging.html\">stage,</a> location of the cancer, and other tissues involved, different operations may be used to remove the cancer and sometimes other tissues near the larynx or hypopharynx. In almost all surgeries, the plan is to take out all of the cancer along with a rim (margin) of healthy tissue around it.</p> \n" +
        "   <p>Surgery might be the only treatment needed for some early stage cancers. It also might be used along with other treatments, like <a href=\"https://www.cancer.orghttps://www.cancer.org/cancer/laryngeal-and-hypopharyngeal-cancer/treating/chemotherapy.html\">chemotherapy</a> or <a href=\"https://www.cancer.orghttps://www.cancer.org/cancer/laryngeal-and-hypopharyngeal-cancer/treating/radiation.html\">radiation</a>, for later stage cancers.</p> \n" +
        "   <p>After the cancer is removed, reconstructive surgery may be done to help make the changed areas look and work better. </p> \n" +
        "<h2>Surgery to treat the cancer</h2> \n" +
        "   <h3>Endoscopic surgery</h3>  \n" +
        "   <p>For this surgery, \n" +
        "     an <a href=\"https://www.cancer.orghttps://www.cancer.org/treatment/understanding-your-diagnosis/tests/endoscopy.html\">endoscope</a> is passed down your throat to find the tumor. The endoscope is a long thin tube with a light and camera on the end of it. This can be done to biopsy and treat some early stage tumors of the larynx. </p> \n" +
        "   <p>The doctor can see the tumor using the camera, and pass long surgical instruments through the endoscope to strip away the superficial layers of tissue on the vocal cords. Most people can speak normally again after this operation.</p> \n" +
        "   <p>Lasers can also be used through the endoscope. They can be used to either vaporize or excise (cut out) the tumor. A drawback of laser surgery is that it leaves nothing behind that can be taken out and tested. If the laser is used to remove part of a vocal cord, it may result in a hoarse voice.</p>  \n" +
        "   <h3>Cordectomy</h3> \n" +
        "   <p>For a cordectomy the surgeon removes all or part of your vocal cords. This can be used to treat very small or superficial glottic (vocal cord) cancers. The effect of this procedure on speech depends on how much of the vocal cords are removed. Removing part of a vocal cord may cause hoarseness. Removing both vocal cords makes normal speech no longer possible.</p> \n" +
        "   <h3>Laryngectomy</h3> \n" +
        "   <p>Laryngectomy is the removal of part or all of the larynx (voice box).</p> \n" +
        "   <p><strong>Partial laryngectomy:</strong> Smaller cancers of the larynx often can be treated by removing only part of the voice box. There are different types of partial laryngectomies, but they all have the same goal: to take out all of the cancer while leaving behind as much of the larynx as possible.</p> \n" +
        "   <p>In a <em>supraglottic laryngectomy</em>, only the part of your larynx above the vocal cords is removed. This procedure can be used to treat some supraglottic cancers, and will allow you to speak normally afterward.</p> \n" +
        "   <p>For small cancers of the vocal cords, the surgeon may be able to remove the cancer by taking out only one side of the larynx (one vocal cord) and leaving the other behind. This is called a <em>hemilaryngectomy</em>. Some speech  remains after this surgery.</p> " +
        "<p><strong>Total laryngectomy: </strong>In this procedure, your entire larynx is removed. The trachea (windpipe) is then brought up through the skin of the front of your neck as a <a href=\"https://www.cancer.orghttps://www.cancer.org/treatment/treatments-and-side-effects/physical-side-effects/ostomies/stomas-or-ostomies.html\">stoma</a> (or hole) that you breathe through (see the picture below). This is called a <em>tracheostomy</em>. When the entire larynx is removed, you can no longer speak normally, but you can learn other ways of speaking. (See <a href=\"https://www.cancer.orghttps://www.cancer.org/cancer/laryngeal-and-hypopharyngeal-cancer/after-treatment.html\"> Living as a Laryngeal or Hypopharyngeal Cancer Survivor</a>) The connection between the throat and the esophagus (swallowing tube) is usually not affected, so you can swallow food and liquids just as you did before the operation.</p> " +
        "<h3>Total or partial pharyngectomy</h3> \n" +
        "  <p>Surgery to remove all or part of the pharynx (throat) is called a <em>pharyngectomy</em>. This operation may be used to treat cancers of the hypopharynx. Often, the larynx is removed along with the hypopharynx. After surgery, you may need reconstructive surgery to rebuild this part of the throat and improve your ability to swallow.</p> \n" +
        "  <h3>Lymph node removal</h3> \n" +
        "  <p>Cancers of the larynx and hypopharynx may spread to the <a href=\"https://www.cancer.orghttps://www.cancer.org/cancer/cancer-basics/lymph-nodes-and-cancer.html\">lymph nodes</a> in the neck. If your doctor thinks that lymph node spread is likely, lymph nodes (and other nearby tissues) may be removed from your neck. This operation, called a <em>neck dissection</em>, is done at the same time as the surgery to remove the main tumor. Doctors determine how likely the cancer has spread to the lymph nodes based on the size and location of the tumor and whether or not the lymph nodes are enlarged on an <a href=\"https://www.cancer.orghttps://www.cancer.org/cancer/laryngeal-and-hypopharyngeal-cancer/detection-diagnosis-staging/how-diagnosed.html\">imaging test</a>.</p> \n" +
        "  <p>There are several forms of neck dissections, ranging from a <em>radical neck dissection</em> to a less extensive <em>selective neck dissection</em>. They differ in the amount of tissue removed from the neck. </p> \n" +
        "  <p>In a full radical dissection, nerves and muscles responsible for some neck and shoulder movement are removed along with the lymph nodes. This might be needed to be sure that all of the lymph nodes likely to contain cancer are removed. If possible, doctors will try to remove less normal tissue to try to keep your shoulder and neck working normally.</p> \n" +
        "  <h3>Thyroidectomy</h3> \n" +
        "  <p>Sometimes\n" +
        "     the cancer spreads into the thyroid gland and all or part of it must be removed. The thyroid sits in the front of your neck and wraps around to the sides of the trachea (windpipe). It makes hormones that control your metabolism and how your body uses calcium.</p> \n" +
        "  <p>If all of the thyroid gland is removed, your body can no longer make the thyroid hormone it needs. In this case, you must take thyroid hormone (levothyroxine) pills to replace the loss of the natural hormone.</p> \n" +
        "  <h2>Other surgeries that may be needed</h2> \n" +
        "  <h3>Reconstructive surgery</h3> \n" +
        "  <p>These operations may be done to help restore the structure or function of areas affected by major surgeries needed to remove the cancer.</p> \n" +
        "  <p><strong>Myocutaneous flaps: </strong>Sometimes a muscle and area of skin may be rotated from an area close to your throat, such as the chest (pectoralis major flap), to reconstruct or rebuild part of your throat.</p> \n" +
        "  <p><strong>Free flaps: </strong>With the advances in microvascular surgery (sewing together small blood vessels under a microscope), surgeons now have many more reconstruction options. Tissues from other parts of your body such as a piece of intestine or a piece of arm muscle can be used to replace parts of your throat.</p>    \n" +
        "  <h3>Tracheostomy/tracheotomy</h3> \n" +
        "  <p>A tracheostomy (tracheotomy) is when the trachea (windpipe) is connected to a hole (stoma) in the front of the neck to help a person breathe by letting air in and out of the lungs through that hole. It may be used in certain cases.</p> \n" +
        "  <p>For instance, after a partial laryngectomy or pharyngectomy, a temporary (short-term) tracheostomy may be needed to help protect your airway while you recover from surgery. To do this, a small plastic tube called a <em>trach tube</em> is put into your trachea through a hole in the front of your neck. The tube stays in place for a short time, and is removed when it's no longer needed. You then breathe through your mouth and nose like you did before.</p> \n" +
        "  <p>As described above, a permanent tracheostomy is needed after a total laryngectomy. In this case, the opening in the trachea is attached to a hole in the skin in the front of your neck. A trach tube or stoma cover may be needed to help keep the tracheostomy hole open. You will breathe through this opening instead of through your mouth and nose.</p> \n" +
        "  <p>If a laryngeal or hypopharyngeal cancer is blocking the windpipe and is too big to remove completely, an opening may be made to connect the lower part of your windpipe to a stoma (hole) in the front of your neck to bypass the tumor and allow you to breathe more comfortably.</p> \n" +
        "  <h3>Gastrostomy tube</h3> \n" +
        "  <p>Cancers in the larynx and hypopharynx may keep you from swallowing enough food to maintain good nutrition. This can make you weak and make it harder to complete treatment.</p> \n" +
        "  <p>A <em>gastrostomy tube (G tube)</em> is a feeding tube that's put through the skin and muscle of your abdomen (belly) and right into your stomach. The tube is often put in place with the help of a flexible, lighted instrument (endoscope) passed down your mouth and into the stomach. This is done while you are sedated. When it's placed through endoscopy, it's called a <em>percutaneous endoscopic gastrostomy</em>, or <em>PEG tube</em>. Another option is to put the tube in during an operation. Once in place, liquid nutrition can be put right into the stomach through the tube.</p> \n" +
        "  <p>Often, the gastrostomy tube is only needed for a short time to help you get enough nutrition during cancer treatment. The tube can be removed once you can swallow again after treatment. It's important to keep swallowing even when you're getting most of your nutrition through a G tube. This helps keep those muscles active and gives you a better chance of going back to normal swallowing after treatment is complete.</p> \n" +
        "  <h2>Possible risks and side effects of surgery</h2> \n" +
        "  <p>All surgery carries some risks, including blood clots, infections, complications from anesthesia, and pneumonia. These risks are generally low but are higher with more complicated operations.</p> \n" +
        "  <p>Patients who have a laryngectomy or pharyngectomy typically lose the ability to speak normally. Some people will need a tracheostomy after surgery. Less extensive operations can also affect speech in some cases. (See <a href=\"https://www.cancer.orghttps://www.cancer.org/cancer/laryngeal-and-hypopharyngeal-cancer/after-treatment.html\">Living as a Laryngeal or Hypopharyngeal Cancer Survivor</a> for more about speech after surgery.)</p> \n" +
        "  <p>Surgeries that affect the throat or voice box can lead to a gradual narrowing (stenosis) of the throat or larynx (if it remains after surgery). Sometimes this can affect breathing. If this happens, you might need a tracheostomy.</p> \n" +
        "  <p>Throat or larynx surgeries may also sometimes affect your ability to swallow. This can affect how you eat, and might be severe enough to require a permanent feeding tube.</p> \n" +
        "  <p>Laryngectomy and pharyngectomy can also lead to the development of a fistula (an abnormal opening between 2 areas that are not normally connected). Surgery may be needed to fix it.</p> \n" +
        "  <p>A very rare but serious complication of neck surgery is rupture of a carotid artery (the large artery on either side of the neck).</p>" +
        // "   <h2>Written by</h2> \n" +
        // " <div class='logo-info rich-content'><p><a href='https://www.cancer.org/cancer/acs-medical-content-and-news-staff.html'>The American Cancer Society medical and editorial content team<br /> \n" +
        // "</a>Our team is made up of doctors and master's-prepared nurses with deep knowledge of cancer care as well as journalists, editors, and translators with extensive experience in medical writing.</p> \n" +
        // "</div> \n" +
        // "</div>";
        "<p>\n Source: <a href=\"https://www.cancer.org/cancer/acs-medical-content-and-news-staff.html\">The American Cancer Society medical and editorial content team.</a> November 27, 2017 </p>";

}